---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

# mlcov

R package for selection of covariate effects using ML. Visit the [PAGE Abstract](https://www.page-meeting.org/?abstract=10996) to learn more.

## Installation

```{r, eval = FALSE}
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}

remotes::install_github("certara/mlcov")
```

# Usage

Import data file:

```{r, message=FALSE}
library(mlcov)

data_file <- system.file(package = "mlcov", "supplementary", "tab11")
data <- read.table(data_file, skip = 1, header = TRUE)
```

Perform covariate search:

```{r}
result <- ml_cov_search(
  data = data,
  pop_param = c("V1","CL"),
  cov_continuous = c("AGE","WT","HT","BMI","ALB","CRT",
                    "FER","CHOL","WBC","LYPCT","RBC",
                    "HGB","HCT","PLT"),
  cov_factors = c("SEX","RACE","DIAB","ALQ","WACT","SMQ")
)
print(result)
```

Generate SHAP plots:

```{r}
generate_shap_summary_plot(
  result,
  x_bound = NULL,
  dilute = FALSE,
  scientific = FALSE,
  my_format = NULL,
  title = NULL,
  title.position = 0.5,
  ylab = NULL,
  xlab = NULL
)

```

Generate residual plots:

```{r}
generate_residuals_plot(data = data, result, pop_param = 'CL')
```

```{r}
generate_residuals_plot(data = data, result, pop_param = 'V1')
```

